### ISSUE TITLE
Add support for Web App for Containers

### ISSUE THREAD

**Issue by xstof** [Azure-Samples/azure-voting-app-redis#13]
The very same sample code could not just be used for demonstrating Kubernetes, but also for showing how Web App for Containers works.  In order to do so, I'd suggest:
- providing an additional environment variable, allowing to pass in the password for Redis (so that Azure Redis cache can be configured to be used with the container image)
- provide an additional Dockerfile which 1) adds support for ssh and 2) flags port 80 as destination

**Comment by neilpeterson** [comment]
@xstof - sorry for the delay, I will review the PR ASAP.

**Comment by xstof** [comment]
Thanks Neil - much appreciated.  Would absolutely help us position the breadth of the container story on Azure using the same little scenario.

**Comment by neilpeterson** [comment]
No problem - merged.
